### ISSUE TITLE
Feature Request: Option to use hard line breaks

### ISSUE THREAD

**Issue by jibin2706** [dasmikko/strapi-tiptap-editor#26]
https://tiptap.dev/api/nodes/hard-break

**Comment by karmaral** [comment]
I was about to open an issue for this as well. I'd be happy to make a PR addressing it if it's okay with the author.

**Comment by dasmikko** [comment]
@karmaral Feel free to make a PR.

**Comment by karmaral** [comment]
@jibin2706 I was looking at this and realized the `StarterKit` already includes the `HardBreak` plugin. I don't know why they weren't working for me in the first place. They seem like they do now.

Do you meant to have it as an option? Otherwise it's already there.

@dasmikko do you think that's worth it? There might be some benefit but I can't imagine a usecase where not having hard breaks would be desired.

**Comment by dasmikko** [comment]
My idea was to make every tiptap extension toggable, so i think it's worth making an option for it

**Comment by karmaral** [comment]
Ah, cool. Alright then.

**Comment by dasmikko** [comment]
This is now released
https://github.com/dasmikko/strapi-tiptap-editor/releases/tag/0.9.0

**Comment by karmaral** [comment]
Cool! I stumbled into a bug when I was tackling this, and it ended up turning into too deep of a rabbithole. I couldn't figure if it was coming from tiptap or somewhere else.

When deactivating the linebreaks and coming back to the editor, if it had any, it wouldn't remove them. It would merely... transform them into nothing (I can't quite remember the how atm). This caused that wherever you clicked on the text, it would reset the cursor to the end of the document until you actually typed something.

Did you encounter this? I wanted to fix it at the time but it most likely meant figuring some way of cleaning the document destructively before re-opening. Last time I checked, if you re-enable the linebreaks, they're still there. Somehow Prosemirror doesn't get mad at the schema.

**Comment by dasmikko** [comment]
If you disable a tag in the settings page, the editor automatically strips the tags from the content. 

The reason you see the line breaks again when enabling, is because the saved content hasn't changed in the database. The editor just doesn't strip the line breaks when initializing.

If you disable line breaks, update the content and save it. Is now permanently gone.
