### ISSUE TITLE
RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by anopid** [dasmikko/strapi-tiptap-editor#58]
on strapi 4.6.0 after 
Install the dependency
`npm install strapi-tiptap-editor`
and 
Build the Strapi Admin
`npm run build`

start dev server.
`npm run develop`

I got this error:

```
RangeError: Adding different instances of a keyed plugin (plugin$)
    at main.c8ae448b.js:3448:28828
    at Array.forEach (<anonymous>)
    at new V1 (main.c8ae448b.js:3448:28774)
    at V1.value (main.c8ae448b.js:3448:30624)
    at v.createView (main.c8ae448b.js:3441:3229)
    at new v2 (main.c8ae448b.js:3441:1039)
    at new v (main.c8ae448b.js:3443:21456)
    at main.c8ae448b.js:3443:27230
    at k6 (main.c8ae448b.js:1136:6971)
    at o.unstable_runWithPriority (main.c8ae448b.js:1164:3947)
```

**Comment by Que-tin** [comment]
Same here...

**Comment by dasmikko** [comment]
Hmmm.. I can't replicate the issue on my end. Can you create a sample project that has this issue, I can test with?

**Comment by manishie** [comment]
Same here...

**Comment by manishie** [comment]
Here's a sample project that has the issue.  Thanks!
[my-project.zip](https://github.com/dasmikko/strapi-tiptap-editor/files/10553241/my-project.zip)

**Comment by dasmikko** [comment]
I managed to replicate the issue now. Thanks for the projekt @manishie. Turns out the issue doesn't appear when i run it in my development environment. 

The issue does seem to not be related with my specific npm package, but rather the tiptap packages
https://github.com/ueberdosis/tiptap/issues/2150

As of now, there isn't much i can do.
